### ISSUE TITLE
nextstrain.org/fetch/: support .json.gz?

### ISSUE THREAD

**Issue by AngieHinrichs** [nextstrain/nextstrain.org#1058]
### Context
The nextstrain.org/fetch/ feature has been indispensable for users of usher.bio to view subtrees with placements of their uploaded sequences.  It works great with Auspice .json files, but currently the .json files have to be stored uncompressed, because it doesn't support .json.gz.  I would like to use compression to save some disk space, especially since I've had requests to make usher.bio subtree output files persist permanently.  I hope accepting compressed .json data would be a straightforward extension to the /fetch/ feature.

### Description
When nextstrain.org gets a /fetch/ request with a .json.gz file instead of .json, it would decompress the fetched data and proceed as usual.

### Examples
Test case with the same tree in uncompressed and gzip-compressed forms:

https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/test.json
https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/test.json.gz

Currently only the former link works.

If you prefer some other form of compression to gzip, that's fine, I'm just suggesting it because it's commonly available on many platforms.

**Comment by jameshadfield** [comment]
We actually store ~all of our Auspice dataset JSONs (e.g. https://data.nextstrain.org/zika.json) with gzip compression (the suffix is still `.json`, but the content is compressed). As long as the response header sets `content-encoding: gzip` the browser decompresses it automagically. This works for /fetch URLs as well ([here's](next.nextstrain.org/fetch/data.nextstrain.org/zika.json) the zika URL above via /fetch). Is this an option for you?

**Comment by AngieHinrichs** [comment]
It must be possible, but the web server where the usher.bio files are stored is an Apache server used by the UCSC Genome Browser (with many other types of files in a shared directory) and administered by others so I have to request any changes to the config.

**Comment by jameshadfield** [comment]
We proxy the JSONs underlying `/fetch/...` URLs through the nextstrain.org server, so I think it'd be possible to interpret `.json.gz` files as gzip compressed and add the required headers as the data passes through the server. I'm not sure whether this is a good idea or not. (And I'm not sure we'll proxy `/fetch` URLs forevermore.) I'll defer to @tsibley.

**Comment by tsibley** [comment]
While we could likely support `.json.gz` ourselves (it's just software after all!), it would be a special-case specific to `/fetch` and require a bit of extra code beyond how we handle compression now.

We do already make outbound requests with `Accept-Encoding: gzip` and indeed hgwdev.gi.ucsc.edu currently responds to such requests with `Content-Encoding: gzip`. It appears to be using `mod_deflate` to gzip-compress on-the-fly. So, over the network between nextstrain.org and hgwdev.gi.ucsc.edu, the data is compressed, saving bandwidth and time. In storage on your side, however, it remains uncompressed, so doesn't solve your problem.

From my perspective, the best solution here would be to make hgwdev.gi.ucsc.edu be able to serve pre-compressed files with `Content-Encoding`, especially since `mod_deflate` is already in use and on-the-fly compression is considered acceptable. Serving pre-compressed content is a common use-case with Apache, and there's [a documentation section/example on how to configure it](https://httpd.apache.org/docs/current/mod/mod_deflate.html#precompressed). Unless it's been administratively forbidden (it's not by default), you should be able to configure this yourself with a `.htaccess` file. Try dropping this `.htaccess` into your `~/public_html/` (or whatever the `/~angie/` URL prefix maps to):

```apache
# Adapted by trs from <https://httpd.apache.org/docs/2.4/mod/mod_deflate.html#precompressed>
<IfModule mod_headers.c>
  # Serve gzip-compressed .json files if they exist and the client accepts gzip.
  RewriteCond "%{HTTP:Accept-encoding}" "gzip"
  RewriteCond "%{REQUEST_FILENAME}\.gz" -s
  RewriteRule "^(.*)\.(json)$"          "$1\.$2\.gz" [QSA]

  # Serve correct content types, and prevent mod_deflate double gzip.
  RewriteRule "\.json\.gz$" "-" [T=application/json,E=no-gzip:1]

  <FilesMatch "\.(json)\.gz$">
    # Serve correct encoding type.
    Header append Content-Encoding gzip

    # Force proxies to cache gzipped and non-gzipped files separately.
    Header append Vary Accept-Encoding
  </FilesMatch>
</IfModule>
```

and then create a `abc.json.gz` file. You should be able to request it as `abc.json` from any HTTP client that sends `Accept-Encoding: gzip`, e.g. browsers, `curl --compressed`, nextstrain.org/fetch.

I've tested this out to make sure I'm giving you a working config: https://nextstrain.org/fetch/tsibley.net/tmp/angie-test.json. On my server, that file only exists as `angie-test.json.gz`.

(It's also possible to add a little more configuration to support clients that _don't_ send `Accept-Encoding: gzip`—by on-the-fly decompressing—but if you don't need that it's simpler to omit it.)

**Comment by AngieHinrichs** [comment]
Thank you @tsibley for writing and testing the .htaccess file!  I will give that a try.  (hgwdev/~angie/ is not the directory where the real files go, it's just a convenient place for me to drop test files, but the same solution should apply.)  If the files work for nextstrain.org and can be downloaded with curl, I don't think I need to worry too much about other clients.  🙂

**Comment by AngieHinrichs** [comment]
For some reason the directory config has `AllowOverride None` which seems to prevent the .htaccess from taking effect, so I have requested a change to `AllowOverride FileInfo` which should allow the Rewrite and Header rules.

**Comment by AngieHinrichs** [comment]
Wit the small config change to allow .htaccess to rewrite and change headers, it seems to be working now, thanks again for your help!

**Comment by tsibley** [comment]
Ah, glad you got it sorted! Looks like I hadn't kept up with the [`AllowOverride` default](https://httpd.apache.org/docs/2.4/mod/core.html#allowoverride)

> AllowOverride None (**2.3.9 and later**), AllowOverride All (2.3.8 and earlier)

and/or was too used to common distro-level default configs that do set `AllowOverride` more permissively.
