### ISSUE TITLE
General process improvement for volunteers

### ISSUE THREAD

**Issue by kimdhamilton** [nextstrain/nextstrain.org#128]
# Overview
While looking into the issue around docs, it was hard to figure out how people can help.  I think some minor improvements will help people quickly determine:
1. Which issues need most urgent help? 
2. What is already being worked on?

This is a description of the problems and some suggestions (need feedback/help from the nextstrain team).

# Problem Details
1. Where is help needed?
I noticed some "getting started" information on the top of [the netstrain.org repo's readme](https://github.com/nextstrain/nextstrain.org), which points to a [project board](https://github.com/orgs/nextstrain/projects/5). That project board is focused on front-end work, but doesn't capture other potentially poachable work I noticed, e.g. [translations-related issues](https://github.com/nextstrain/ncov/issues) in the ncov repo.

2. What is being worked on?
In general, it would be good to know at a glance what's poachable vs in-progress, whether that's though "unassigned" queries (i.e. ensure everything working on is assigned, so people don't have to read through each issue) or a project board structured like: 

   poachable | in progress | in review

# Questions:
1. Are you looking for volunteers on this repo as well? https://github.com/nextstrain/ncov?
2. In general, what are the highest pri repos? From a scan, it seems to be auspice, ncov, and nextstrain.org (the latter for general documentation help)
3. Do we want to pull in all poachable issues to the above project board? Or create multiple project boards? (I have no preference)
4. Which way do you prefer to show that an issue being worked on? We need either assignments, tags, or the ability to demonstrate progress in the project board.
5. For tags. I noticed a "Please take this issue" tag in one of the repos, but it would be good to know for the key repos if you have conventions.

# Next steps
Need input from the nextstrain team on the above. Based on that, I can add this to the README (or create a new doc focused on "how to dive in and help immediately")

**Comment by jameshadfield** [comment]
Thanks @kimdhamilton -- these suggestions are great. I've discussed this with @huddlej and we've come up with a plan which we think will address the points you raise. Your comments on the plan are very welcome!

### Project Boards

We are committed to using project boards to manage issue priority, and keep track of what is being worked on. Currently there is only one project board: [Front-end nCoV-related work to be done](https://github.com/orgs/nextstrain/projects/5). We propose the following project boards to manage all things nextstrain, with each board attracting a different skill set:

(A) The current board -- front end work -- which grabs issues from https://github.com/nextstrain/nextstrain.org and https://github.com/nextstrain/ncov/auspice

(B) A bioinformatics board -- this is essentially  https://github.com/nextstrain/augur but may include requests for scripts in other pathogen-specific repos

(C) A translations board (which captures contributions solicited for  https://github.com/nextstrain/ncov). @huddlej and I talked about maintaining a project board "Translations" with columns such as "Not picked up", "In progress", "Needs validation by a native speaker" & "Done" , with issues replaced each week as new narratives become available and need translating. However @cassiawag is 💯 on this so I'll let her choose the most appropriate format for how to manage these. 

(D) A documentation project? Or are these issues best subsumed by boards A-C?

### Pointing people towards these project boards

We propose 
* creating a CONTRIBUTING.md for each repo which, as well as outlining the nextstrain.org contributing process (see more below) points to these boards as places to see outstanding issues.
* Creating a pinned issue on each repo to direct people to these boards instead of perusing the issue list (although that's fine too)
* Creating links in the README.md which point to the board(s) most appropriate for the repo

### Indicating what's being worked on

This is really important for us to keep tabs on what's happening. We'd like people to self-assign (if this is possible?) or add a comment indicating they're working on it. We can then adjust the position in the boards as appropriate. 

### Labels

@huddlej has proposed we systematically go through all the repos and use the following labels, which I think is a great idea. We are aware this won't be possible over night, and won't prevent us adding issues to the project boards. 
Priority: low / moderate / high
Difficulty: easy / moderate / difficult
Type: bug / enhancement / duplicate
Avaiability: Needs triage / good first issue / help wanted
Components affected: docs / narratives / frontend / backend / scientific-builds
Status: accepted / do-not-merge / breaking / blocking / needs review


### Contributing guide
We are going to try to make a nextstrain-wide CONTRIBUTING.md (and will copy it into each repo) outlining our code-of-conduct, what's expected, and to point people to the appropriate project boards. We should be able to have this up in the coming days.

**Comment by huddlej** [comment]
@jameshadfield Regarding copying the contributing guide across repos, it looks like [GitHub supports default contributing guides (and other common files) through a special repository called .github](https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file).

It might still be preferable to have the contributing guide in nextstrain.org's repo and link to it from other repo READMEs, so we don't forget where the contributing guide lives.

**Comment by huddlej** [comment]
I have started adding and aligning issue labels for [nextstrain.org](https://github.com/nextstrain/nextstrain.org/labels) and [auspice](https://github.com/nextstrain/auspice/labels). In the auspice repo we already have a "please take this issue" label while the nextstrain.org repo has a "help wanted" label. The auspice label is a lot less ambiguous, so I think our availability labels in the comment above should be:

needs triage / good first issue / please take this issue

If that seems reasonable, I'll rename "help wanted" on nextstrain.org's labels to "please take this issue".

**Comment by sidneymbell** [comment]
This is all excellent. @huddlej -- let me know when you're working on the default `.github` repo and I'll add a Code of Conduct, etc., as well.

**Comment by kimdhamilton** [comment]
this sounds fantastic. I can write this up as a PR to the https://github.com/nextstrain/nextstrain.org README.md as an additional entrypoint to direct people.

**Comment by huddlej** [comment]
@kimdhamilton [Here is our working draft of the contribution guide](https://hackmd.io/qta45a9DS1O-OjyhfclZ6A?view) so far based on work from @jameshadfield, @sidneymbell, and myself. Very excited for any ways this can be improved upon and fleshed out to a useful document.

**Comment by sidneymbell** [comment]
@kimdhamilton -- Thank you so much for all your help here! I've started to create a lot of this infrastructure over at https://github.com/nextstrain/.github 

I've decomposed the suggestions listed here into issues in that repository (and am closing this one for tidiness); would you take a look and self-assign any pieces that you'd like to drive?
