### ISSUE TITLE
Second tree URL loading is (sometimes) broken

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/nextstrain.org#131]
Auspice, and nextstrain.org support loading two trees via the `<tree1>:<tree2>` URL structure. For instance https://nextstrain.org/flu/seasonal/h3n2/ha/2y:flu/seasonal/h3n2/na/2y works as intended.

This is broken for some datasets through nextstrain.org but not auspice. E.g. running auspice locally, http://localhost:4000/ncov:ncov works as intended (even if it's not scientifically very interesting) however https://nextstrain.org/ncov:ncov does not work

**Comment by tsibley** [comment]
This is because of the top-level routing:

https://github.com/nextstrain/nextstrain.org/blob/master/server.js#L103-L145

Paths like `/ncov:ncov` never make it to Auspice because they don't match one of those routes. The issue only affects single-part core datasets like `/ncov` and `/zika`.

I believe adding a line like the following:

```js
...coreBuilds.map(url => url + ":*"),
```

to the routing code linked above would suffice.
