### ISSUE TITLE
Add Open Graph and Twitter Card meta tags for rich embeds/previews

### ISSUE THREAD

**Issue by tsibley** [nextstrain/nextstrain.org#134]
[Open Graph](https://ogp.me) is a microformat that specifies `<meta>` tags which can be added to the `<head>` of pages in order to provided structured data about the page. Apps like Facebook, Twitter, and Slack will look for these tags and use them to provide richer embeds/previews when someone links to the page.

[Twitter Cards](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/abouts-cards) build upon Open Graph to provide some extra Twitter-specific information. These may or may not be necessary in our case.

By setting this up for nextstrain.org pages, links in social apps will display a better preview. Doing so will require changes to both Gatsby and the Nextstrain extensions to Auspice.

One challenge will be picking an appropriate "cover" image, since nearly all of the fancy visuals of Nextstrain are dynamic and not static. A first-pass option might be to use the pathogen cards on the front page of Nextstrain. Later, if desired, we could provide an endpoint which generates screencaps of the tree or map or something (probably with significant caching).

**Comment by victorlin** [comment]
It seems like these tags for the nextstrain.org static site have already been implemented in [SEO.js](https://github.com/nextstrain/nextstrain.org/blob/938aabcab71993c1ebdd938c92227147d9fe92f6/static-site/src/components/SEO/SEO.jsx). See this [Open Graph Check of https://nextstrain.org](https://opengraphcheck.com/result.php?url=https%3A%2F%2Fnextstrain.org) - the tags are there. It's worth noting that this seems to be outdated and the `og:image` points to a non-existent file.

The problem is when linking to a page for datasets or narratives. Examples:

- [Open Graph Check for https://nextstrain.org/ncov](https://opengraphcheck.com/result.php?url=https%3A%2F%2Fnextstrain.org%2Fncov)
- [Open Graph Check for https://nextstrain.org/narratives/ncov/sit-rep/2020-03-20](https://opengraphcheck.com/result.php?url=https%3A%2F%2Fnextstrain.org%2Fnarratives%2Fncov%2Fsit-rep%2F2020-03-20)

Since these are generated by auspice (the HTML base seems to be [auspice/index.html](https://github.com/nextstrain/auspice/blob/master/index.html)), I believe this issue should be moved over to that repository, unless you all would rather track it here.

**Comment by psthomas** [comment]
I think the `og:image` [file](https://nextstrain.org/static/logos/nextstrain-logo-small.png) is missing because the siteLogo url in [siteConfig.js](https://github.com/nextstrain/nextstrain.org/blob/master/static-site/data/SiteConfig.js) points to the location in the repo (`"/static/logos/nextstrain-logo-small.png"`) rather than the public location after the static site is built (`"/logos/nextstrain-logo-small.png"`). I think this is due to the way Gatsby handles [absolute links](https://www.gatsbyjs.org/docs/static-folder/#adding-assets-outside-of-the-module-system) to static files.

Twitter cards should [fall back](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#opengraph) to Open Graph tags if Twitter tags aren't present, but I don't think this is working. Their [card validator](https://cards-dev.twitter.com/validator) finds the meta tags but doesn't render a preview, so it might just make sense to add the Twitter tags as well. I can experiment and make a pull request.

Do you have a preference for the "Summary", or "Summary with Large Image" cards? I like the low-key look of the Summary card more but it's up to you.
![cards](https://user-images.githubusercontent.com/14950467/78401761-133a1b80-75bf-11ea-98f8-6dc2c5773d0d.png)

**Comment by TAM360** [comment]
Hi @tsibley , first time contributor here. I would like to work on this issue. However, I am finding it a bit difficult to understand the flow of repository even after going through all of the documentation. I would appreciate your input here.

**Comment by tsibley** [comment]
Thanks @psthomas! I too have a preference for the more condensed "Summary" cards. We'll try to review your PR soon.

**Comment by psthomas** [comment]
Ok, thanks! The approach I took was to read in the url and splash image relationships from the Cards, and then export a react component that uses them to sync the tags in Auspice. This component could eventually point to screencaps if you used something like Puppeteer to create them during the build.

I've tested all of the static site tags and they work, and the Auspice tags work locally. The main question I have is whether the Auspice tags will be visible to social media bots because some of them aren't rendered on the frontend until after the dataset loads. This would mainly be a problem for the description tags, which are taken from the metadata after it loads.

**Comment by genehack** [comment]
Currently, the OpenGraph meta-elements are only appearing in fully hydrated pages, which is generally not the version of the page that is seen when OpenGraph-consuming applications (e.g., Twitter, Facebook, Mastodon, etc.) 

The proper fix here, it seems to me, is getting the metadata to be available in the "un-hydrated" version of the page (i.e., the page version that you see when running `curl` against the site, not the page version that you see in a browser's web inspector). From what I can tell by experimenting with a small demo Next.js app, the currently "correct" way to do this is with the [Metadata API](https://nextjs.org/docs/app/building-your-application/optimizing/metadata), which is only available with the App Router. 

Consequently, I am going to build on my [recent metadata for feed auto-discovery PR](https://github.com/nextstrain/nextstrain.org/pull/1016) to convert the blog over from the Pages Router to the App Router, fixing the OpenGraph meta tag generation along the way.
