### ISSUE TITLE
All ncov builds page

### ISSUE THREAD

**Issue by eharkins** [nextstrain/nextstrain.org#180]
**Context**  
As discussed on a call today, we would like to have a page like https://nextstrain.org/ncov-sit-reps but that shows all the builds for ncov (global and regional).

**Description**   
UI details are an ongoing conversation and this issue is place to discuss them. Some suggestions included:
* a more or less identical UI to https://nextstrain.org/ncov-sit-reps
* a table showing various meta info about each build
* a searchable list
* an interactive map with links to builds

Perhaps we can also solicit more designs/advice from the UI designer who helped with designs for the splash page and https://nextstrain.org/ncov-sit-reps.
**Examples**  
https://nextstrain.org/ncov-sit-reps
https://bedfordlab.slack.com/archives/C116R9PR7/p1586372885144200

**Possible solution**   
Hopefully reuse lots of code from https://nextstrain.org/ncov-sit-reps

**Comment by trvrb** [comment]
Here's my suggested UI:

![sars-cov-2-select](https://user-images.githubusercontent.com/1176109/84455869-53e39000-ac13-11ea-9828-4c71996e6f39.png)

Borrowing from my thoughts on generic dataset select from before https://github.com/nextstrain/nextstrain.org/issues/62.

**Comment by emmahodcroft** [comment]
The downside of this is that I feel it's really not useful to figure out where I need to go if I want to see a dataset of Spain, Switzerland, or Connecticut. I think we need to give some more geographical guidance here. I have to say, this is a pretty big turn-off for me. I think unless you know these groups to start with (and what region they're likely to work with), this isn't very usable to find a dataset.

I recognise this means there'll possibly have to be come kind of more manual mapping between the groups/communities & what countries/states offer, but I think we kind of need to do this somehow - otherwise you have to expand every single one of these to figure out what locations are available.

I also think it's kind of weird that the main Nextstrain builds are listed at the same level as community & other builds. I think it would be ok to highlight these a little more - these are probably still what a large number of people want - maybe through the half-size tiles that James made? Or even quarter-size. 

Though this definitely won't be sustainable long-term, I think I'd rather have:
Nextstrain builds at the top, as some kind of quarter-size tiles or similar.
Grouping by region, and within each of those, the builds available, saying what country/state they are for. Possibly groups by country/state in another expandable, if needed.
The group who is maintaining it should be listed, but the focus should be on the region covered, IMO.

**Comment by tsibley** [comment]
I agree with Emma. I think a set of geographic headings and subheadings + lists of the builds would work better than a fancier table and also be easier to put up right now. Something really simple, like:

![image](https://user-images.githubusercontent.com/79913/84536739-542b6c00-aca3-11ea-8b80-5fecd0340fa4.png)


By not using a table, it's also easier to add custom notes contextualizing multiple builds for a region, for example.

**Comment by trvrb** [comment]
Brilliant! I really like this Tom. It would be nice to promote people / groups responsible for contributing. But this could be a simple:

---------------------------
**USA**

National (SPHERES)

* California (SPHERES)
  - Northern California (CZI BioHub)
  - Southern California (Scripps)
* Massachusetts (Broad Institute)
* Minnesota (MDH)
---------------------------

**Comment by tsibley** [comment]
Yeah, I think giving credit like that would be great. :-)

**Comment by trvrb** [comment]
Also, in a discussion on Slack (https://bedfordlab.slack.com/archives/C7SDVPBLZ/p1591986159076200), we thought that the best endpoint for this dataset listing is nextstrain.org/sars-cov-2. If we make this page now we can iterate and then when we're happy we can add a redirect from nextstrain.org/ncov to nextstrain.org/sars-cov-2.

**Comment by rneher** [comment]
Would this "all-build" page also be the place where we want to put a tool to assign clades? Or link to a subdomain `clades.nextstrain.org/sars-cov-2`? Or similar? The idea would be a static web-app that takes a set of sequences and gives back clade assignments and mutations. Could hence also be used as QC tool. 

Alternatively, we could have something like this in auspice. That would make sense if we ultimately highlighted neighbors of these sequences in the tree. But auspice is already incredibly busy...

our prototype of this is currently here:
https://github.com/neherlab/webclades

**Comment by tsibley** [comment]
I think in terms of clarity as an index, we wouldn't want to put the tool directly on that page. It could be linked from there as well well as other places.

**Comment by emmahodcroft** [comment]
Is there any chance we could have something like this drafted (as Trevor says, we could iterate on it further!) by Wed 24 June, in time for a SPHERES call highlighting Nextstrain & in particular group builds? But I say that having no idea how hard this is to throw together. If someone can make a basic page with some levels, and reminds me where the list is of "all the builds we know about" is, I'm happy to start populating a skeleton page 😄

**Comment by eharkins** [comment]
@emmahodcroft I would love to help with this! I'll get started on drafting something up this afternoon / tomorrow that can then be populated and iterated on.

**Comment by tsibley** [comment]
If it's useful as a starting point, here's a Markdown file I'd started a day or two ago, slightly cleaned up just now: https://gist.github.com/tsibley/126f95c25ef0cea7888f9aaa938ef615

I was pulling it together trying to get a handle on what a data file of this build index might have to look like.

**Comment by eharkins** [comment]
Done in #185. Closing this in favor of #182 for discussion of future improvements to this page.
