### ISSUE TITLE
Use async iterators/generators for pulling paginated items from S3 Buckets

### ISSUE THREAD

**Issue by kairstenfay** [nextstrain/nextstrain.org#212]
From @tsibley:
> Thanks everyone for addressing this TODO I'd marked. I think it'd be nice to use async iterators/generators in the future for this sort of thing, which makes the code more imperative and easier to follow. It looks like the AWS JS SDK doesn't have built-in support for async iterators (unlike the Python SDK, which does), but it'd be possible with a small wrapper function.

See [original comment](https://github.com/nextstrain/nextstrain.org/pull/211#issuecomment-681081577) on the [related PR](https://github.com/nextstrain/nextstrain.org/pull/211).

**Comment by genehack** [comment]
This issue has been sitting untouched for over four years. We’re trying to get a good handle on our open issues and pull requests, so that we can reliably use them as a backlog of things we hope to work on, so I'm going to go ahead and close it out. 

If you think this issue reflects an ongoing issue or other work that still should be a priority to accomplish, please re-open the issue and explain why.

**Comment by tsibley** [comment]
This was actually resolved by b326340b3c4bb6fe35afc2af6117609e69291083.
