### ISSUE TITLE
Fetch metadata for all builds in sars-cov-2 build catalogue

### ISSUE THREAD

**Issue by eharkins** [nextstrain/nextstrain.org#269]
https://github.com/nextstrain/nextstrain.org/pull/266 is the proof of principle here. It goes through the list of builds in the sars-cov-2 build catalogue, and fetches the auspice dataset from the url listed in each build entry. This dataset is used to attach metadata about the dataset (from the dataset's `meta` property) to the build entry and write it out to an "augmented" build catalogue file that is used by nextstrain.org/sars-cov-2 to display these metadata about each build on the map there (e.g. when the dataset was last updated).

Currently this is limited to build entries with urls of a [certain format](https://github.com/nextstrain/nextstrain.org/pull/266/files#diff-60e76e88a4190ff6fcbe051a0db3f4289f7eb71dfa79f8f2f10d7e96b1fc6162R17).

Three things need to happen to remove this limitation:
- rewrite (or remove altogether) the [function used to determine if a build entry can be augmented according to its url](https://github.com/nextstrain/nextstrain.org/pull/266/files#diff-60e76e88a4190ff6fcbe051a0db3f4289f7eb71dfa79f8f2f10d7e96b1fc6162R13)
- go through the build catalogue and manually enforce that all build urls are running an auspice server that will return 1 dataset, so that we can uniformly fetch one dataset per build url.
- rewrite [fetching function code](https://github.com/nextstrain/nextstrain.org/pull/266/files#diff-60e76e88a4190ff6fcbe051a0db3f4289f7eb71dfa79f8f2f10d7e96b1fc6162R283) that gets the dataset name from the url and fetches the dataset using charon.

**Comment by genehack** [comment]
This issue has been sitting untouched for over three years; it looks like the work in #266 was eventually merged in #271. We’re trying to get a good handle on our open issues and pull requests, so that we can reliably use them as a backlog of things we hope to work on, so I'm going to go ahead and close it out. 

If you think this issue reflects an ongoing issue or other work that still should be a priority to accomplish, please re-open the issue and explain why.
