### ISSUE TITLE
/users/:name response has a 404 Not Found status code instead of 200 Ok

### ISSUE THREAD

**Issue by tsibley** [nextstrain/nextstrain.org#293]
**Current Behavior**  
https://nextstrain.org/whoami responds with a 302 Redirection to https://nextstrain.org/users/trs (my username is _trs_), which responds with a 404 Not Found. The page content is as expected, just the status code is misleading.

**Expected behavior**  
/users/:name endpoint returns a 200 Ok response.

**Comment by jameshadfield** [comment]
I encontered this as well while doing some work for a forthcoming PR. It occurs as none of our handlers in `server.js` handle this route, so it falls through to 
```js
app.get("*", (req, res) => {
  utils.verbose(`Sending Gatsby entrypoint for ${req.originalUrl}`);
  res.sendFile(gatsbyAssetPath(""), {}, (err) => {
    // This error callback is used to display the 404 page
    if (err.code === 'EISDIR') res.status(404).sendFile(gatsbyAssetPath("404.html"));
  });
});
```
Which, as far as I can understand, will _always_ use the error callback since `gatsbyAssetPath("")` doesn't exist (it's a directory). Gatsby's generated pages have client-side code which will end up rendering the users page, but how exactly this happens is unclear to me. 

This handling style, including the `404` was introduced via dad77d80ed180e2757e5a8d58ba36e811f8fbdc4. Before that it was simpler but, from memory, didn't display 404 pages as expected.
```js
app.get("*", (req, res) => {
  utils.verbose(`Sending Gatsby entrypoint for ${req.originalUrl}`);
  res.sendFile(gatsbyAssetPath("index.html"));
```
