### ISSUE TITLE
Show spinner while waiting for datasets data to arrive

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/nextstrain.org#304]
**Description**  
When loading pages with a `<DatasetSelect/>` component there is often a lag while the relevant data is fetched there the table is not displayed. A spinner (or similar) should be displayed to communicate that some UI is forthcoming.

**Examples**  
See auspice for an implementation of the Nextstrain spinner. 

**Possible solution**

Given the current code structure, this could be implemented as a `<LoadingSpinner/>` component which parent components would call similar to:

```jsx
{ this.state.errorFetchingData ?
  <ErrorMessage/> :
  this.state.dataLoaded ?
    <DatasetSelect/> :
    <LoadingSpinner/>
}
```

An alternate approach (untested) is to represent the (fetched) datasets as a Promise and pass that as a prop, letting <DatasetSelect/> handle the loading / error cases. This is preferable as it doesn't require the parent component to handle the logic for error handling / loading state.

```jsx
// parent component
constructor(props) {
    this.datasetsPromise = fetch(jsonUrl)
      .then((res) => res.json())
      .then((res) => maniplateData(res))
}
render () {
  ...
  <DatasetSelect datasets={this.datasetsPromise}/>
}
// DatasetSelect component
constructor(props) {
   this.state = {loading: true, datasets: undefined, error: false}
}
componentDidMount() {
  try {
    this.setState({datasets: await this.props.datasets, loading: false})
  } catch (e) {
    this.setState({error: true, loading: false})
  }
}
```

**Comment by genehack** [comment]
I see a spinner when datasets are loading, so I'm going to guess this was done at some point and this issue just got orphaned.

**Comment by victorlin** [comment]
This issue is about the dataset listings, for example on a groups page:

https://github.com/user-attachments/assets/57f27078-9d0d-4cbf-a61a-c3bb947760a1

As mentioned in https://github.com/nextstrain/nextstrain.org/issues/353#issuecomment-887952364, there is now "Data loading..." text instead of showing nothing/"no datsets available". I think this issue is then specifically to change the "Data loading..." text to a spinner. Probably safe to close as "won't fix".
