### ISSUE TITLE
URLs allow underscores in place of slashes in dataset paths

### ISSUE THREAD

**Issue by tsibley** [nextstrain/nextstrain.org#432]
Some dataset (and presumably narrative) routes allow using underscores instead of slashes in the URL path, e.g. <https://nextstrain.org/groups/blab/ncov_early-outbreak_root-A> instead of <https://nextstrain.org/groups/blab/ncov/early-outbreak/root-A>.

Underscores work because of an implementation detail about how we're backing those files that is leaking through. The presence of underscores breaks many assumptions made by nextstrain.org and Auspice, a minor example of which is Auspice's dataset selector. Other broken assumptions could lead to more serious breakage, such as authz bugs (though I don't think this is the case currently).

We should prevent the unexpected behaviour of underscores working in order to make the system consistent to reason about.

**Possible solutions**  
- Change route patterns to exclude `_` (e.g. `:dataset([^_]*)` instead of `*`)
- Change Source/Dataset/etc model classes to reject paths with underscores

**Comment by schneid44** [comment]
Hi!

My name is Justin and I'm a computer science student at the University of Michigan. For a final project another student and I are tasked with working on an open source project. I was wondering if this issue is still relevant and ready to be worked on or if you had any other suggestions about what could be worked on. We are both seniors, familiar with Javascript, and expected to do about 15-20 hours of work. Thanks in advance!

**Comment by tsibley** [comment]
@schneid44 Hi again, and thanks again for your interest in contributing. This issue is still relevant. Of the two possible solutions listed above, I'm not sure we have a preference yet. The preferred solution probably depends on what the implementation of each ends up looking like and the impact it has on the rest of the codebase. Would you be interested in evaluating/prototyping them? If an alternate potential solution arises, that would also be worth considering.

**Comment by skorman** [comment]
@tsibley,

Thanks for the quick response! @schneid44 and I are going to be working together on this project. We have been able to build and run the server locally and would be glad to start evaluating solutions for this issue. We will update with our progress as we continue.

**Comment by skorman** [comment]
We have created an initial prototype for how to deal with this situation. Our idea was use middleware to return a 404 error whenever there is a URL with an underscore. We forked the repository, and the changes can be found at https://github.com/nextstrain/nextstrain.org/compare/master...jesum44:Underscores-in-place-of-slashes-schneid44-&-skorman?expand=1

We do also have more questions which would help us out for completing and creating tests for this issue.

- Are there specific base routes where this should be applied? For example, only under the /groups endpoint?
- Is it okay to reject all paths that contain an underscore? Will there ever be a situation that we don't want to reject a URL with an underscore? (and if so, what would this situation be).
- Should we return a 404 response when this occurs, or is there other expected behavior?


Let us know what you think of this solution, or what other solutions we should consider.

Thanks!

**Comment by jesum44** [comment]
Hey @tsibley, just wondering if you got the chance to look at our code. We'd really appreciate any feedback / next steps that you have! 

For testing purposes, is it possible that we could get the AWS credentials to be able to test the code changes that we make locally?

We were also planning on working on #330 Let us know if you have any specific recommendations or tips for this issue. Thanks!

**Comment by tsibley** [comment]
@skorman @jesum44

Ah, it's not acceptable to reject any request with an underscore in the path, as there's no reason those are invalid globally and making them so would be surprising to future dev work. This issue is specifically about fixing the leak of an implementation detail related to dataset and narrative paths the app serves. Did you consider either of the solutions proposed in the issue description up top?

> For testing purposes, is it possible that we could get the AWS credentials to be able to test the code changes that we make locally?

We can't share AWS credentials with you. You should still be able to test locally against our core public datasets (e.g. `/flu/seasonal/h3n2/ha/2y` vs. `/flu/seasonal/h3n2_ha_2y`) without elevated access to any AWS resources.

**Comment by jesum44** [comment]
@tsibley 

We tried implementing the solution you suggested where we change the model classes to reject routes with slashes in them.
Here is the code from our forked repository: https://github.com/nextstrain/nextstrain.org/compare/master...jesum44:underscore?expand=1

What kind of error should be returned when the user goes to a route with an underscore? Please let us know any comments or suggestions that you have.
