### ISSUE TITLE
Re-title "Private Nextstrain Groups" section header on splash page or restrict tiles to private groups

### ISSUE THREAD

**Issue by kairstenfay** [nextstrain/nextstrain.org#80]
@jameshadfield [brought this up in our #nextstrain-general Slack channel](https://bedfordlab.slack.com/archives/C7SDVPBLZ/p1578945475043700) when he realized he was seeing `blab` under Private Nextstrain Groups. 

In that Slack thread, @trvrb describes how he wants `blab` to exist as a public Nextstrain group. 

Ideally, we would show users their "Nextstrain Group Membership" including public & private with something to make it clear that links to private groups are only showing up because a user (with access) is logged in.

**Comment by trvrb** [comment]
GitHub distinguishes between public and private repos via an book vs a lock icon and additional adds "Private" next to private repos. I'd think towards something like this.

**Comment by jameshadfield** [comment]
I currently see the following:

![image](https://user-images.githubusercontent.com/8350992/72304732-4f539380-36d6-11ea-9310-a158cb24db31.png)

This is certainly a bug, although one that's not really affecting many people (yet).

Solution a: We rename the title to remove "Private", and then use a padlock icon (or similar) to indicate which groups are indeed private. If a user is not logged in, they should also see a groups section, although I don't think this should be at the top.

Solution b: Limit the groups tiles to private only (i.e. `blab` removed from the above screenshot). Doesn't stop us having a seperate set of tiles for public groups.

---

Note that I believe that this issue is only showing up due to me being a member of the `blab` _cognito_ group, which matches a group in the sources, and thus gets a tile. While cognito groups and nextstrain groups are different, we seem to have settled on a consistent naming scheme whereby group `x` is backed by S3 bucket `nextstrain-x` and, if private, then there exists a cognito group `x` which authenticated users are members of. If the group is public then to keep things consistent we shouldn't have a cognito group `x`.

**Comment by trvrb** [comment]
I can try to mock something up in sketch. I was thinking that near the top of the page should be something like "Groups you belong to" and have all groups someone is a member in, both public and private (with an icon or something to distinguish between them). We could even maybe get rid of the intro paragraph for logged in users. They don't need to see the pitch. Alternatively, this sort of information only lives in someone's `/users/` page. It might be less confusing that way. (This might be my preference)

Then separately, we should have tiles down below (perhaps directly after Community) with subset of all public groups that is the same for all users.

**Comment by tsibley** [comment]
@jameshadfield 

> If the group is public then to keep things consistent we shouldn't have a cognito group `x`.

Not quite. Every Nextstrain Group should be backed by a Cognito group, for future authorization purposes.
