### ISSUE TITLE
Sessions don't refresh group membership information without logout/login cycle

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/nextstrain.org#81]
Right now the code (as I understand it) fetches and stores cognito groups upon login (https://github.com/nextstrain/nextstrain.org/blob/master/authn.js#L76). This can lead to situations where (i) the code doesn't see "new" _cognito_ groups until the user re-logs-in and (ii) the code sees groups which have been removed until the user logs in again.

@tsibley is this the general way things are done (this is not my area of expertise)? Could we poll the Cogntio API every ~24 hours to update without requiring the user to re-login?

**Comment by tsibley** [comment]
@jameshadfield The current behaviour is a temporary one, which arose from necessary expediency in the original manifestation the INRB group.

As [I mentioned earlier](https://github.com/nextstrain/nextstrain.org/pull/77#discussion_r365933603), we can improve this lag/re-login issue in the future by refreshing user details from Cognito on ~every nextstrain.org request, ideally with a short-lived TTL cache in between to avoid multiple hits to Cognito across a rapid series of nextstrain.org requests.

**Comment by tsibley** [comment]
Recent thinking on two approaches that combined will address session staleness:

1. Store the authn tokens in the session instead of storing the user info extracted from the initial login token (which is then discarded). Validate the stored token and extract the user info on each request, with automatic behind-the-scenes renewal by the server as necessary. This is identical to the Nextstrain CLI token handling, and will let us control how often the server refreshes info from Cognito by tuning the token lifetimes in the Cognito client config for the server.

2. For group memberships specifically, we can track on the server side when things like group membership changes happen (once we extend our API to cover membership management) and record a timestamp that says "don't accept tokens created before X for user Y". This is a basic implementation of an authn revocation system. The system will then a) force a web session with a stale but not expired token to be renewed by the server (per above) and b) force API requests with a stale but not expired token to be retried after renewal by the API client (which means we'd want to implement this in Nextstrain CLI).
