### ISSUE TITLE
`build-ref-matrix` failures preventing deployment

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/nextstrain.org#899]
The recent CI action [failed](https://github.com/nextstrain/nextstrain.org/actions/runs/9392436971/job/25867073780#step:4:11) due to

```console
 ./scripts/get-resource-index-ref-matrix: line 12: HEROKU_TOKEN: The HEROKU_TOKEN environment variable is required.
Error: Process completed with exit code 1.
```

(and thus correctly wasn't deployed). I re-ran it and it failed again (same error). A run ~20 mintutes previous [succeeded](https://github.com/nextstrain/nextstrain.org/actions/runs/9392329947).

**Comment by tsibley** [comment]
I looked into this (cause I got a Slack notification) and observed that the `HEROKU_TOKEN` is resolving to empty:

![image](https://github.com/nextstrain/nextstrain.org/assets/79913/d15466ec-3457-484b-ae7c-775078d21b6e)

but is defined as:

https://github.com/nextstrain/nextstrain.org/blob/d05fac2f194ab16a2c59c51626bae31d65a10179/.github/workflows/index-resources.yml#L44-L45

which implies to me that either GitHub Actions is experiencing issues resolving secrets (but there's nothing on https://githubstatus.com), or that particular workflow-triggering event precludes access to secrets, possibly because it was a commit/merge by Dependabot.

**Comment by tsibley** [comment]
I suspect we need to [configure secrets for Dependabot](https://github.com/nextstrain/nextstrain.org/settings/secrets/dependabot) separately from [secrets for GitHub Actions](https://github.com/nextstrain/nextstrain.org/settings/secrets/actions). Even though Actions is running here, it's because of Dependabot.

**Comment by joverlee521** [comment]
Ah [dependabot doesn't have access](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#accessing-secrets)

> When a Dependabot event triggers a workflow, the only secrets available to the workflow are Dependabot secrets. GitHub Actions secrets are not available. Consequently, you must store any secrets that are used by a workflow triggered by Dependabot events as Dependabot secrets

**Comment by tsibley** [comment]
Yeah, was just about to link to https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#responding-to-events

**Comment by tsibley** [comment]
> If you have a workflow that will be triggered by Dependabot and also by other actors, the simplest solution is to store the token with the permissions required in an action and in a Dependabot secret with identical names.

That is a frustrating way to do things.

**Comment by joverlee521** [comment]
Added `HEROKU_TOKEN_READ_PROTECTED` to dependabot secrets and [rerunning the workflow](https://github.com/nextstrain/nextstrain.org/actions/runs/9392436971)

**Comment by jameshadfield** [comment]
Thanks all! I figured it was something to do with "environments", and it kinda was but not what GitHub calls "environments".

P.S. There's some Dependabot secrets that we no longer have as actions secrets that we may want to remove

**Comment by victorlin** [comment]
> P.S. There's some Dependabot secrets that we no longer have as actions secrets that we may want to remove

#903
