### ISSUE TITLE
Add splash tile / pathogen showcase entry for `seasonal-cov`

### ISSUE THREAD

**Issue by genehack** [nextstrain/nextstrain.org#940]
### Context
[Suggested by @jameshadfield](https://github.com/nextstrain/nextstrain.org/pull/939#pullrequestreview-2152492485) during review of #939 

Creating a new issue for this because I'm not sure if the intent of the showcase is for there to be a tile for _everything_ or just for "notable" datasets. If the latter, I'm not sure `seasonal-cov` qualifies?

To be clear, I think we're talking about a tile in the showcase on https://nextstrain.org/pathogens, not the top-level splash page. 

Opinions sought!

**Comment by joverlee521** [comment]
Should we showcase any pathogen that is being automatically updated? I'd hope any pathogen that we think is important enough automate is also "notable"

**Comment by victorlin** [comment]
I believe the original list added in f57bf94a257127f0bc1d9ea8fdc6d4af7fff3b02 was short because the showcase was not expandable and thus implicitly capped at 9 entries at max width of `.container`. Now that it's expandable, I would propose adding at the very least any automatically updated pathogen, if not all available pathogens and repurposing it as more like a "table of contents".

**Comment by victorlin** [comment]
For splash page tiles defined by [featured-analyses.yaml](https://github.com/nextstrain/nextstrain.org/blob/-/static-site/content/featured-analyses.yaml), my understanding is that @trvrb is maintaining this so I would run any new entries through him to determine if/where to place the tile relative to existing tiles.

**Comment by victorlin** [comment]
> Now that it's expandable, I would propose adding at the very least any automatically updated pathogen, if not all available pathogens and repurposing it as more like a "table of contents".

If adding every available pathogen, I would also propose alphabetical sorting to align with how we are now sorting groups. The current sorting is something along the lines of [some "popular" items] + [other items based on time of addition] which is  pretty arbitrary.

**Comment by trvrb** [comment]
If the showcase gets too long, it no longer serves the purpose to highlight new / notable pages. I wouldn't have every automatically updated pathogen (this is what /pathogens is for). I'd also be rotating out previous highlights pretty judiciously. That said, I think the current splash page could handle up 18 cards maximum (3 rows of 6). So we don't have to rotate out quite yet. The top 4-6 should have lots of thought as they're above the fold (as many users won't click the carat).

In this particular case, I think rotating in seasonal CoV near the bottom would be fine, but it would rotate out sooner than most.

>If adding every available pathogen, I would also propose alphabetical sorting to align with how we are now sorting groups.
It's important that pathogens of current scientific / public health focus stay at the top of the list. It will need to be manually tended to.

**Comment by victorlin** [comment]
There are two separate "showcases" being conflated here:

1. "Featured analyses" on https://nextstrain.org/
![image](https://github.com/user-attachments/assets/ad904349-2c42-4f59-97a6-9179b681a078)

2. "Showcase resources" on https://nextstrain.org/pathogens
![image](https://github.com/user-attachments/assets/d7b95034-2034-4c09-9b88-366589e2e753)

Everything said above in https://github.com/nextstrain/nextstrain.org/issues/940#issuecomment-2351941145 I agree is applicable to (1). I am proposing adding every pathogen and sorting alphabetically to (2). I think this issue is mostly about (2):

> To be clear, I think we're talking about a tile in the showcase on https://nextstrain.org/pathogens, not the top-level splash page.

**Comment by trvrb** [comment]
Ah! Sorry, this was my failure at reading comprehension. Yes! I agree that the best thing for nextstrain.org/pathogens is to include a tile for every pathogen. It feels a little weird to me that if sorting alphabetically, we'll lose SARS-CoV-2 from the "above-the-line" row of tiles that's a single click away. But, I think this is okay as the splash page showcase should maintain SARS-CoV-2 front and center. /pathogens can be more of an encyclopedia in this case and so yes I think alphabetical makes sense.

**Comment by victorlin** [comment]
Done in 2103297425e8e23d8ddfcadce3b235c6a012abdf

**Comment by trvrb** [comment]
Awesome!
